apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: registry-storage
  namespace: openshift-image-registry
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 60Gi # Adjust size as needed
  storageClassName: nfs-client # e.g., ocs-storagecluster-cephfs
